apiVersion: build.knative.dev/v1alpha1
kind: Build
metadata:
  name: nodejs-service
spec:
  timeout: 20m
  serviceAccountName: builder
  source:    
    git:
      url: https://github.com/KarthikBashyam/nodejs-docker.git
      revision: master
  template:
    name: knative-build-template
    arguments:    
    - name: IMAGE
      value: registry.hub.docker.com/bashdocker/nodejs-helloworld:latest