apiVersion: build.knative.dev/v1alpha1
kind: Build
metadata:
  name: nodejs-service-build
spec:
  timeout: 50m
  serviceAccountName: build-bot
  source:    
    git:
      url: https://github.com/KarthikBashyam/nodejs-docker.git
      revision: master
  template:
    name: knative-build-template
    arguments:    
    - name: IMAGE
      value: docker.io/bashdocker/nodejs-helloworld:latest